yuhu_challenge/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("list/", views.UserListCreate.as_view()),
    path("", views.HomePageView.as_view(), name="home"),
]

yuhu_challenge/api_v1/urls.py
from django.urls import path

from .views import ToDoDetail, ToDoListCreate

app_name = "api_v1"

urlpatterns = [
    path("todos/", ToDoListCreate.as_view(), name="list"),
    path("todos/<int:pk>/", ToDoDetail.as_view(), name="detail"),
    # path("items", ToDoItemViewSet.as_view(), name="todos"),
]

yuhu_challenge/todos/urls.py
from django.urls import path

from .views import CombinedTodoView, ToDoDeleteView, ToDoUpdateView, ToogleToDoView

app_name = "todos"

urlpatterns = [
    path("delete/<int:pk>", ToDoDeleteView.as_view(), name="delete"),
    path("update/<int:pk>/", ToDoUpdateView.as_view(), name="update"),
    path("toggle_is_done/<int:pk>/", ToogleToDoView.as_view(), name="toggle_is_done"),
    path("", CombinedTodoView.as_view(), name="list"),
]

yuhu_challenge/yuhu_challenge/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("todos/", include("todos.urls")),
    path("api_v1/", include("api_v1.urls")),
]

yuhu_challenge/accounts/models.py
from django.db import models

# Create your models here.

yuhu_challenge/api_v1/models.py
from todos.models import ToDoItem

yuhu_challenge/todos/models.py
from django.contrib.auth.models import User
from django.db import models


class ToDoItem(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    description = models.CharField(max_length=500, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    due_date = models.DateTimeField(default=None, blank=True, null=True)
    is_done = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

yuhu_challenge/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({"placeholder": "Email"})

yuhu_challenge/todos/forms.py
from django import forms

from .models import ToDoItem


class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = [
            "name",
            "description",
            "due_date",
        ]

        widgets = {
            "due_date": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }


class ToDoDelete(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = ["id"]

yuhu_challenge/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import TemplateView
from rest_framework.generics import ListCreateAPIView

from .forms import CustomUserCreationForm
from .serializers import UserSerializer


class UserListCreate(ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class SignUpView(View):
    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, "signup.html", {"form": form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home")
        print("Error")
        print(form.errors)
        return render(request, "signup.html", {"form": form, "errors": form.errors})


class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, "login.html", {"form": form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")  # Redirect to home page after successful login
        return render(request, "login.html", {"form": form})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect("home")


class HomePageView(TemplateView):
    template_name = "home.html"

yuhu_challenge/api_v1/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView

from .models import ToDoItem
from .serializers import ToDoItemSerializer


class ToDoListCreate(ListCreateAPIView):
    queryset = ToDoItem.objects.all()
    serializer_class = ToDoItemSerializer


class ToDoDetail(RetrieveUpdateDestroyAPIView):
    queryset = ToDoItem.objects.all()
    serializer_class = ToDoItemSerializer

yuhu_challenge/todos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView, UpdateView

from .forms import ToDoDelete, ToDoForm
from .models import ToDoItem


class CombinedTodoView(LoginRequiredMixin, TemplateView):
    model = ToDoItem
    form_create = ToDoForm
    form_delete = ToDoDelete
    template_name = "todos/todo_list.html"

    def _get_context(self, request, reset_form: bool = True):
        context = {}
        context["form"] = self.form_create()
        paginator = Paginator(
            self.model.objects.filter(user__email=request.user.email).order_by(
                "-created_at"
            ),
            5,
        )
        page_number = 1
        form = self.form_create()

        if request.method == "GET":
            page_number = request.GET.get("page", 1)

        if request.method == "POST" and not reset_form:
            form = self.form_create(request.POST)

        todos = paginator.get_page(page_number)
        context["todos"] = todos
        context["form"] = form
        return context

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self._get_context(request))

    def post(self, request, *args, **kwargs):
        form = self.form_create(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
        return self.render_to_response(self._get_context(request, form.is_valid()))


class ToDoDeleteView(LoginRequiredMixin, DeleteView):
    model = ToDoItem
    success_url = reverse_lazy("todos:list")


class ToDoUpdateView(LoginRequiredMixin, UpdateView):
    model = ToDoItem
    form_class = ToDoForm
    template_name = "todos/update_todo.html"
    success_url = reverse_lazy("todos:list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


import json


class ToogleToDoView(View):
    model = ToDoItem

    def patch(self, request, *args, **kwargs):
        data = json.loads(request.body)
        pk = data.get("pk")
        record = self.model.objects.get(pk=pk)
        record.is_done = not record.is_done
        record.save()
        return HttpResponse(status=204)

yuhu_challenge/accounts/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
    <nav>
        <ul>
            {% if user.is_authenticated %}
                <li>Welcome, {{ user.username }} | <a href="{% url 'logout' %}">Logout</a></li>

            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    <h1>Welcome to the To Do app!</h1>
    {% if user.is_authenticated %}
        <li> <a href="{% url 'todos:list' %}">Go to the TO-DOs</a></li>
    {% endif %}
</body>
</html>

yuhu_challenge/accounts/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'signup' %}">Register</a></li>
        </ul>
    </nav>
    <h2>Login Form</h2>
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <!-- Add form fields here -->
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <button type="submit">Login</button>
    </form>
</body>
</html>

yuhu_challenge/accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'login' %}">Login</a></li>
        {% if user.is_authenticated %}
            <li>Welcome, {{ user.username }} | <a href="{% url 'logout' %}">Logout</a></li>
        {% endif %}
    </ul>
    <h2>Signup Form</h2>
    <form method="post" action="{% url 'signup' %}">
        {% csrf_token %}
        <!-- Email field will be rendered automatically -->
        <input type="text" name="username" placeholder="Username">
        <input type="email" name="email" placeholder="Email">
        <input type="password" name="password1" placeholder="Password">
        <input type="password" name="password2" placeholder="Confirm Password">
        <button type="submit">Sign Up</button>
    </form>

    {% if errors %}
        <div class="error-messages">
            <ul>
                {% for field, errors in errors.items %}
                    <li>{{ field }}:</li>
                    <ul>
                        {% for error in errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</body>
</html>

yuhu_challenge/todos/templates/todos/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django To-Do{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'todos/styles.css' %}">
</head>
<body>
    <header>
        <nav>
            Time to get things done {{ user.username }} ! | <a href="{% url 'logout' %}">Logout</a>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
       Aaron Garibay
    </footer>
</body>
</html>

yuhu_challenge/todos/templates/todos/todo_list.html
{% extends "todos/base_generic.html" %}

{% block content %}
<h2>Todo List</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="buttons-container">
        <button type="submit" class="button button-primary">Add New Task</button>
        <button type="reset" class="button button-warning">Clear form</button>
    </div>
</form>
<div class="todos">
{% for todo in todos %}
<div class="todo-item">
    <div class="item-info">
        <input type="checkbox" id="checkbox_{{ todo.id }}"  onchange="handleCheckboxChange(this)" {% if todo.is_done  %} checked {% endif %}>
        <div class="item-values">
            <strong id="name_text_{{ todo.id }}" class="{% if todo.is_done %} todo-item-text-done {% else %} todo-item-text {% endif %}">{{ todo.name }} - </strong>
            {% if todo.description %}
                <span id="description_text_{{ todo.id }}" class="{% if todo.is_done %} todo-item-text-done {% else %} todo-item-text {% endif %}">{{ todo.description }}</span>
            {% else %}
                <span id="description_text_{{ todo.id }}" class="{% if todo.is_done %} todo-item-text-done {% else %} todo-item-text {% endif %}">No Description</span>
            {% endif %}<strong>-</strong>

            {% if todo.due_date %}
                <span>{{ todo.due_date|timeuntil }}  <strong>-</strong>
            {% endif %}
        
            <i>{{ todo.user.email }}</i>
        </div>
    </div>
    <div class="action-buttons">
        <form method="post" action="{% url 'todos:delete' todo.id %}">
            {% csrf_token %}
            <button type="submit" class="button button-warning">Delete</button>
        </form> 
        <a href="{% url 'todos:update' todo.id %}" class="button-anchor-secondary" >Modify</a>
    </div>
</div>

{% empty %}
<p>No To-Do items found.</p>
{% endfor %}
</div>

<!-- Pagination -->
<div class="pagination">
    <span class="step-links">
        {% if todos.has_previous %}
            <a href="?page=1" class="first-page-link">&laquo; first</a>
            <a href="?page={{ todos.previous_page_number }}" class="prev-page-link">previous</a>
        {% endif %}

        <span class="current">
            Page {{ todos.number }} of {{ todos.paginator.num_pages }}.
        </span>

        {% if todos.has_next %}
            <a href="?page={{ todos.next_page_number }}" class="next-page-link">next</a>
            <a href="?page={{ todos.paginator.num_pages }}" class="last-page-link">last &raquo;</a>
        {% endif %}
    </span>
</div>

<script>
    function handleCheckboxChange(checkboxElement) {
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');
        const is_done = checkboxElement.checked;
        const pk = checkboxElement.id.split("_")[1];

        const url = `/todos/toggle_is_done/${pk}/`;

        fetch(url, {
            method: 'patch',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            },
            body: JSON.stringify({
                pk,
                is_done,
            }),
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            let textStyles = [
                document.getElementById(`name_text_${pk}`),
                document.getElementById(`description_text_${pk}`)
            ]
            if(is_done === true) {
                textStyles.forEach(element => element.classList.replace("todo-item-text", "todo-item-text-done")
                );
            } else {
                textStyles.forEach(element => element.classList.replace("todo-item-text-done", "todo-item-text"))
            }
        })
        .catch(error => {
            console.error('There has been a problem with your fetch operation:', error);
        });
}

</script>

{% endblock %}

yuhu_challenge/todos/templates/todos/update_todo.html
{% extends "todos/base_generic.html" %}

{% block content %}
<h2>Edit To-Do Item</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
   
    <div class="buttons-container">
        <button type="submit" class="button button-primary">Save Changes</button>
        <a href="{% url 'todos:list' %}" class="button-anchor-secondary ">Return</a>
    </div>
</form>


{% endblock %}